### ISSUE TITLE
no module named 'ui'

### ISSUE THREAD

**Issue by bisraelsen** [usc-psychsim/psychsim#10]
trying to execute `__main__.py` in the `psychsim` directory returns the error:
```
Traceback (most recent call last):
  File "__main__.py", line 7, in <module>
    from ui.mainwindow import Ui_MainWindow
ModuleNotFoundError: No module named 'ui'
```
After investigating the code further I can't find a `ui` module anywhere. Does it exist anymore?

**Comment by pynadath** [comment]
It does exist in the PsychSim main repo; I was just minimal in setting up the ATOMIC repository. But let me port it over, because it might be fun to play with the graph visualization.

**Comment by pynadath** [comment]
Oops, this has been pushed to the repo.
