### ISSUE TITLE
Does it make sense to rename `getActions`?

### ISSUE THREAD

**Issue by bisraelsen** [usc-psychsim/psychsim#14]
using `agent.actions` returns the full action set of an agent. Using `agent.getActions()` returns the legal actions given the current state.

Does it make sense to rename `getActions` to `getLegalActions` to make the function more self-explanatory and differentiate form `agent.actions`?

**Comment by pynadath** [comment]
Yes it does. Now renamed (and calling getActions gives a DeprecationWarning so as to not be completely opaque).
