### ISSUE TITLE
Problem with updating beliefs about models

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#16]
I'm getting an error when updating the state via `state *= policy` (line 370, `world.py`), where the policy has an `"if"` branch involving comparing a model, ie `1.000*Agent's __MODEL__ == maximize-pos`, where `maximize-pos` is the name of an agent's model.

The problem seems to be in the `desymbolizeThreshold` of `plane.py`, here:
```python
        if isinstance(threshold,str):
            try:
                return eval(threshold,globals(),table)
            except NameError:
                # Undefined reference: assume it'll get sorted out later
                return threshold
```

The `threshold` is the name of the model, and `table` has the corresponding integer index, but the function does not fetch it, instead it tries to evaluate the string?

To replicate, run: `model-learning/model_learning/examples/reward_model_fit.py` of the `model-learning` repository.

**Comment by pynadath** [comment]
Does it work if you remove the hyphen from the model name?

**Comment by pedrodbs** [comment]
Ha! I don't receive that error anymore. It works with `maximize_pos` though. 
In general, does it mean we can't use operator symbols in names?

PS: I think we can close this one.
