### ISSUE TITLE
thresholdRow() computes >= operation?

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#17]
From my tests, it seems that the `thresholdRow()` function computes the `>=` (greater than or equal to) operation and not the `>` operation as indicated in the documentation (both the code documentation and the readthedocs: https://psychsim.readthedocs.io/en/latest/modeling.html#hyperplanes).

Just to confirm if this is true or I am doing something wrong.

**Comment by pynadath** [comment]
Hmm, it should be >. Let me check.

**Comment by pynadath** [comment]
It was using an epsilon to avoid any float problems, but did so backwards. I've removed the epsilon altogether, because it's kind of silly (if the threshold is so critical for a continuous variable, the modeler will probably make sure there are no floating point issues).
