### ISSUE TITLE
Bug in state.py in an indexing operation

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#3]
Bug in state.py, __iter__ function of VectorDistributionSet.
When i gets divided, it becomes a float, and then the index becomes a float causing the indexing operation to fail.

```python
for substate in substates:
                element = domains[substate][i % len(domains[substate])]
                ...
                i /= len(domains[substate])
                ...
```

**Comment by pynadath** [comment]
Ah, that's right /= is now float division in Python3, so I've changed it to be //= which will return an int.
