### ISSUE TITLE
Agents' decisions are not independent in "parallel" turn order

### ISSUE THREAD

**Issue by pedrodbs** [usc-psychsim/psychsim#5]
When setting a parallel turn order, agent's decisions are not independent from each other.
Namely, the issue is that there's an implicit order, provided by the set() structure, and as agents decide in this order, subsequent agents' decisions are "grounded" by this decision, rather than being independent.

The problem is in the stepPolicy() function in world.py:
```python
            for name in toDecide:
                # This agent might have a turn now
                agent = self.agents[name]
                decision = self.agents[name].decide(state,horizon,actions,None,tiebreak,
                                                    agent.getActions(state),debug=debug.get(name,{}))
                try:
                    actions[name] = decision['policy']
```

Eg, for the second agent deciding, `actions` already contains the decision of the 1st agent, hence top-level decisions are not independent. 
See the `small-examples/game-theory-tom.py` example, where both agents should 'defect', but the second agent 'cooperates' because the first one "already" defected when its time to decide.

**Comment by pynadath** [comment]
Huh, I thought I already fixed that, so it must've gotten clobbered in the merge. The simplest fix is to pass in "None" instead of "actions" when calling agent.decide in stepPolicy, no?

**Comment by pedrodbs** [comment]
This is solved in the linked pull request.
Basically I do:
```python
            # if no one has decided yet, agents' decisions should be independent
            if actions is None:
                turn = {}
            else:
                turn = copy.copy(actions)
```
and then send `turn` to `decide()`. 
`actions` still stores the resulting decisions.
